"use client"

// meta data currently messing up app
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// react-query
import { QueryClient, QueryClientProvider, useQuery } from 'react-query'

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // bring in query client
  const queryClient = new QueryClient()
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <body className={inter.className}>{children}</body>
      </QueryClientProvider>
    </html>
  );
}
